# wrangler.toml - Cloudflare Workers Configuration for Squad Backend
name = "squad"
main = "index.js"
compatibility_date = "2025-09-01"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

[vars]
NODE_ENV = "production"
CLIENT_URL = "http://localhost:3000"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "super.yahyaaa@gmail.com"
R2_ENDPOINT = "https://fe19d3afc8180ebd5792c34afb1f85af.r2.cloudflarestorage.com"
R2_BUCKET_NAME = "discord"
R2_PUBLIC_URL = "https://pub-e7047da4406c44fb8e93f1578db119fd.r2.dev"
